### ISSUE TITLE
Add STARTTLS Support for IMAP Connections

### ISSUE THREAD

**Issue by ghost** [cry-inc/dmarc-report-viewer#4]
I encountered an issue when attempting to connect to my IMAP server. It seems the current implementation lacks support for STARTTLS, which is required by my server configuration. Without this feature, the connection fails and produces the following error:
```
ERROR Failed updated cycle: Failed to get mails: Failed to create TLS stream with IMAP server: received corrupt message of type InvalidContentType
```

**Comment by cry-inc** [comment]
Can you try again with the latest version from master? I added some code to add support for STARTTLS. You can see the changes in commit 4ad4f65942e74f1fc25af3cc229b27b7af6b0385.

To enable STARTTLS support you have to use the new optional argument `--imap-starttls` and set the port to 143 (`--imap-port 143`). You can also use the ENV variables `IMAP_STARTTLS=true` and `IMAP_PORT=143`, they are doing the same.

Please let me know if this works for you!
